security:
    providers:
        in_memory:
            memory:
                users:
                    guest:
                        password: $2y$12$9IBBxfZ1kgR0K50XcD6Ri.CfUQF30JqJsaUiWl3foVFnb8Jh7SJ5u
                        roles: 'ROLE_USER'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/wedding, roles: ROLE_USER }